import { Aspect, Ocean } from "./schema";
const interpretations: any = [
  {
    category: {
      categoryName: Ocean.Openness,
      veryLow: {
        part1: "You are very low in openness, which you are not interested in novelty, art, literature, abstract thinking, philosophy, and aesthetics.",
        part2: "Those very low in openness dislike or are averse to complexity, intellectual problems, or challenges. They are extremely routine and usually have singular likes, which means they are not interested in exploring different cultural events or types of movies, concerts, plays, or art shows. In other words, they tend to stay with what they know or were brought up in, find satisfaction in doing things the traditional way.",
        part3: "People very low in openness tend dislike having to write or read; however, they tend to stay to “mainstream material” if they do. They have a very narrower range of interests, and a more conventional vocabulary. They can think abstractly and learn, when necessary, but it will exhaust them. They also may have difficulty getting their thoughts across to others (especially if low in extraversion).",
        part4: "People very low in openness thrive in situations or occupations that are more routinized and predictable. They can be better suited entry-level, repetitive, rote positions because they don’t need to generate new ways of doing things and are less inclined to want to try new things or shake things up. This also means they are less entrepreneurial and more appreciative of conventional employment (particularly if average or above in conscientiousness).",
        part5: "Note: the lower the openness, the narrower and more focused a person’s interests. This means they can settle on a single path in life, specialize in a skill, and create a singular identity. Because of this they less frequently undermine their own convictions or beliefs by excessive questioning and are passionate about what they know.",
      },
      low: {
        part1: "You are low in openness, which you are not interested in novelty, art, literature, abstract thinking, philosophy, and aesthetics.",
        part2: "Those low in openness dislike or are averse to complexity, intellectual problems, or challenges. They are extremely routine and usually have singular likes, which means they are not interested in exploring different cultural events or types of movies, concerts, plays, or art shows. In other words, they tend to stay with what they know or were brought up in, find satisfaction in doing things the traditional way.",
        part3: "People low in openness tend dislike having to write or read; however, they tend to stay to “mainstream material” if they do. They have a very narrower range of interests, and a more conventional vocabulary. They can think abstractly and learn, when necessary, but it will exhaust them. They also may have difficulty getting their thoughts across to others (especially if low in extraversion).",
        part4: "People low in openness thrive in situations or occupations that are more routinized and predictable. They can be better suited entry-level, repetitive, rote positions because they don’t need to generate new ways of doing things and are less inclined to want to try new things or shake things up. This also means they are less entrepreneurial and more appreciative of conventional employment (particularly if average or above in conscientiousness).",
        part5: "Note: the lower the openness, the narrower and more focused a person’s interests. This means they can settle on a single path in life, specialize in a skill, and create a singular identity. Because of this they less frequently undermine their own convictions or beliefs by excessive questioning and are passionate about what they know.",
      },
      modLow: {
        part1: "You are moderately low in openness, which you are less interested in novelty, art, literature, abstract thinking, philosophy, and aesthetics.",
        part2: "Those moderately low in openness are not interested in the complexity of intellectual problems or challenges and prefer to stay away complexity. They are routine and usually have singular likes, which means they are not very interested in exploring different cultural events or types of movies, concerts, plays, or art shows, although they may do such things on occasion. In other words, they tend to stay with what they know or were brought up in, find satisfaction in doing things the traditional way.",
        part3: "People moderately low in openness tend avoid writing less and read somewhat less than average; however, they tend to stay to “mainstream material” if they do read or write. They have a narrower range of interests, and a more conventional vocabulary. They can think abstractly and learn when necessary, but may sometimes have difficulty getting their thoughts across to others (particularly if they average or below in extraversion).",
        part4: "People moderately low in openness thrive in situations or occupations that are more routinized and predictable. They can be better suited entry-level, repetitive, rote positions because they don’t need to generate new ways of doing things and are less inclined to want to try new things or shake things up. This also means they are less entrepreneurial and more appreciative of conventional employment (particularly if average or above in conscientiousness).",
        part5: "Note: the lower the openness, the narrower and more focused a person’s interests. This means they can settle on a single path in life, specialize in a skill, and create a singular identity. Because of this they less frequently undermine their own convictions or beliefs by excessive questioning and are passionate about what they know",
      },
      average: {
        part1: "You are average in openness to experience and may sometimes be characterized by a couple of the following descriptors:  smart, creative, exploratory, intelligent, and visionary.",
        part2: "People average in openness are moderate in their intellect and curiosity.  Depending of the situation or content they may enjoy reading, but may not have as large of a vocabulary as someone who is high in the trait. They can think, learn, generate ideas with average speed.  Sometimes they can see old things in novel ways or appreciate them as they are. Occasionally, they will be able to see problems in different ways and may have solution to go with it. They are not compelled to seek change.",
        part3: "Those average in openness are more suited for situations or jobs that are routine and predictable. They don’t mind being placed in categories, pecking orders, set structures. For this reason, they are suited for entry-level, repetitive, rote positions, but may seek to grow in that position.  They are not known to shake things up or be rebellious unless pushed into that position and for a specific cause.",
        part4: "ndividuals average in openness are not as entrepreneurial as someone higher in this trait, which means have a lower interest in new ventures for any reason: profit, curiosity, personal transformation, etc.",
        part5: "Note: The higher the openness the greater the interest in things. Because of this, settling or finding a single path in life, specialization, or identity is very difficult. This can clash with their neuroticism and/or conscientiousness. If also high in neuroticism, they will habitually undermine their own convictions and beliefs, feeling more lost and anxious. If they are low in conscientiousness, they will be “under-achievers” because despite the ability to be smart, learn quickly, or be creative, they do not act on their ideas.",
      },
      modHigh: {
        part1: "You are moderately high in openness to experience and are likely to be characterized by others as very smart, creative, exploratory, intelligent, and visionary.",
        part2: "People moderately high in openness are known for their intellect and curiosity.  They enjoy reading about many subjects, which is accompanied by large vocabulary. They can think, learn, generate ideas, speak quickly.  They can see old things in novel ways, which gives them the ability to see problems in different ways as well many possible solutions. For this reason, they are compelled to seek change.",
        part3: "Those moderately high in openness are not suited well for situations or jobs that are routine and predictable. They struggle to be placed in categories, pecking orders, set structures. For this reason, they are ill-suited for entry-level, repetitive, rote positions. If they are in such as position, they will generate new ways to do things, which are usually not welcome at entry level positions.  They are known to shake things up (especially if disagreeable and assertive) and be rebellious (particularly if average or below in conscientiousness).",
        part4: "Individuals moderately high in openness are drawn by the entrepreneurial spirit, which means have a high interest in new ventures for any reason: profit, curiosity, personal transformation, etc.",
        part5: "Note: The higher the openness the greater the interest in things. Because of this, settling or finding a single path in life, specialization, or identity is very difficult. This can clash with their neuroticism and/or conscientiousness. If also high in neuroticism, they will habitually undermine their own convictions and beliefs, feeling more lost and anxious. If they are low in conscientiousness, they will be “under-achievers” because despite the ability to be smart, learn quickly, or be creative, they do not act on their ideas.",
      },
      high: {
        part1: "You are high in openness to experience and are likely to be characterized by others as very smart, creative, exploratory, intelligent, and visionary.",
        part2: "People very high in openness are known for their intellect and curiosity.  They enjoy reading about many subjects, which is accompanied by large vocabulary. They can think, learn, generate ideas, speak quickly.  They can see old things in novel ways, which gives them the ability to see problems in different ways as well many possible solutions. For this reason, they are compelled to seek change.",
        part3: "Those high in openness are not well in situations or jobs that are routine and predictable. They struggle to be placed in categories, pecking orders, set structures. For this reason, they are ill-suited for entry-level, repetitive, rote positions. If they are in such as position, they will generate new ways to do things, which are usually not welcome at entry level positions.  They are known to shake things up (especially if disagreeable and assertive) and be rebellious (particularly if average or below in conscientiousness).",
        part4: "Individuals high in openness are drawn by the entrepreneurial spirit, which means have a high interest in new ventures for any reason: profit, curiosity, personal transformation, etc.",
        part5: "Note: The higher the openness the greater the interest in things. Because of this, settling or finding a single path in life, specialization, or identity is very difficult. This an clash with their neuroticism and/or conscientiousness. If also high in neuroticism, they will habitually undermine their own convictions and beliefs, feeling more lost and anxious. If they are low in conscientiousness, they will be “under-achievers” because despite the ability to be smart, learn quickly, or be creative, they do not act on their ideas.",
      },
      veryHigh: {
        part1: "You are very high in openness to experience and are likely to be characterized by others as very smart, creative, exploratory, intelligent, and visionary. ",
        part2: "People very high in openness are known for their intellect and curiosity.  They are prolific readers of any subject, which is accompanied by large vocabulary. They can think, learn, generate ideas, speak with great speed.  They can see old things in strikingly new ways, which gives them the ability to see problems in different ways as well many possible solutions. For this reason, they are compelled to seek change.",
        part3: "Those high in openness are not well in situations or jobs that are routine and predictable. They struggle to be placed in categories, pecking orders, set structures. For this reason, they are ill-suited for entry-level, repetitive, rote positions. If they are in such as position, they will constantly generate new ways to do things, which are usually not welcome at entry level positions.  They love to shake things up (especially if disagreeable and assertive) and be rebellious (particularly if average or below in conscientiousness).",
        part4: "Individuals very high in openness are drawn by the entrepreneurial spirit, which means have a high interest in new ventures for any reason: profit, curiosity, personal transformation, etc).",
        part5: "Note: The higher the openness the greater the interest in things. Because of this, settling or finding a single path in life, specialization, or identity is very difficult. This an clash with their neuroticism and/or conscientiousness. If also high in neuroticism, they will habitually undermine their own convictions and beliefs, feeling more lost and anxious. If they are low in conscientiousness, they will be “under-achievers” because despite the ability to be smart, learn quickly, or be creative, they do not act on their ideas.",
      },
    },
    aspect1: {
      aspectName: Aspect.AestheticOpenness,
      veryLow: {
        part1: "You are very low in openness to creativity, which means you are not drawn to beauty, art, or creative endeavors and may find those types of activities to be wastes of time.",
        part2: "Those very low in creativity are not driven to find a creative ability or express it; they will also not be negatively affected by this.  They are rarely affected by the aesthetic power of color and architecture. They are not collectors, and very rarely pursue it passionately. They are less imaginative, more rarely daydream, and reflect less often than average. If they enjoy music or other art forms, their taste tends toward the conventional and popular. They are less often musical or artistic themselves and do not become immersed in a book, or a movie, or in their own thoughts.",
        part3: "People very low in creativity are stable and conventional in their life choices, and for this reason will do better at careers that are of singular focus with less complexity",
        part4: "Note: The lower the creativity, the more practical or focused they may be (especially if high in conscientiousness). This means that they will have an easier time finding a career they can stay in and an identity they are comfortable with.",
        part5: "Women are higher in openness to creativity than men. "
      },
      low: {
        part1: "You are low in opennesst o creativity, which means you are not drawn to beauty, art, or creative endeavors and may find those types of activities to be wastes of time.",
        part2: "Those low in creativity are not driven to find a creative ability or express it; they will also not be negatively affected by this.  They are rarely affected by the aesthetic power of color and architecture. They are not collectors, and very rarely pursue it passionately. They are less imaginative, more rarely daydream, and reflect less often than average. If they enjoy music or other art forms, their taste tends toward the conventional and popular. They are less often musical or artistic themselves and do not become immersed in a book, or a movie, or in their own thoughts.",
        part3: "People low in creativity are stable and conventional in their life choices, and for this reason will do better at careers that are of singular focus with less complexity.",
        part4: "Note: The lower the creativity, the more practical or focused they may be (especially if high in conscientiousness). This means that they will have an easier time finding a career they can stay in and an identity they are comfortable with.",
        part5: "Women are higher in openness to creativity than men"
      },
      modLow: {
        part1: "You are moderately low in openness to creativity, which means you are not particular drawn to beauty, art, or creative endeavors.",
        part2: "hose moderately low in creativity are not driven to find a creative ability or express it; they will also not be negatively affected by this.  They are less sensitive to the aesthetic power of color and architectural form. They are not typically collectors, and very rarely pursue it passionately. They are less imaginative, more rarely daydream, and reflect less often than average. If they enjoy music or other art forms, their taste tends toward the conventional and popular. They are less often musical or artistic themselves and do not become immersed in a book, or a movie, or in their own thoughts.",
        part3: "People of moderately low in creativity are more stable and conventional in their life choices, and for this reason will do better at careers that are of singular focus with less complexity.",
        part4: "Note: The lower the creativity, the more practical or focused they may be (especially if high in conscientiousness). This means that they will have an easier time finding a career they can stay in and an identity they are comfortable with.",
        part5: "Women are higher in openness to creativity than men. "
      },
      average: {
        part1: "You are average in openness to creativity, which means you can occasionally enjoy beauty, art, music, etc. but are not driven by it.",
        part2: "Those average in creativity do not need an outlet for their creative ability, or content with keeping things at a hobby level. They are adaptable to their environments and do not necessary need it to be aesthetic or creative. For example, they are not overly sensitive to color and architectural form and like to collect creative trinkets. They have a normal imagination and don’t usually get lost reflecting on things. They enjoy music, books, movies, and any other form of entertainment but don’t get lost in it. They may respond to beauty, creativity, and art on occasion.",
        part3: "Note: The higher the creativity, the more impractical or flighty they may be (especially if low in conscientiousness). This means that they may have a very hard time monetizing their creativity or turning it into a career. However, creativity is necessary for entrepreneurial success.",
        part4: "Women are higher in openness to creativity than men.",
      },
      modHigh: {
        part1: "You are moderately high in openness to creativity, which means you enjoy beauty, art, music, etc.",
        part2: "Those high in creativity need an outlet for their creative ability, or they will wither. They also need environment to match their creative personality. For example, they are sensitive to color and architectural form, and like to collect creative trinkets They have a powerful imagination and can get lost reflecting on things. They moved by music, books, movies, and any other form of stories to the point that they may be oblivious to the outside world. They respond very strongly to beauty, creativity and art and may be creative themselves in those areas.",
        part3: "Note: The higher the creativity, the more impractical or flighty they may be (especially if low in conscientiousness). This means that they may have a very hard time monetizing their creativity or turning it into a career. However, creativity is necessary for entrepreneurial success.",
        part4: "Women are higher in openness to creativity than men.",
      },
      high: {
        part1: "You are high in openness to creativity, which means you appreciate beauty, art, music, etc.",
        part2: "Those high in creativity need an outlet for their creative ability, or they will wither. They also need environment to match their creative personality. For example, they are sensitive to color and architectural form, and like to collect creative trinkets They have a powerful imagination and can get lost reflecting on things. They moved by music, books, movies, and any other form of stories to the point that they may be oblivious to the outside world. They respond very strongly to beauty, creativity and art and may be creative themselves in those areas.",
        part3: "Note: The higher the creativity, the more impractical or flighty they may be (especially if low in conscientiousness). The means they may have a very hard time monetizing their creativity or turning it into a career. However, creativity is necessary for entrepreneurial success.",
        part4: "Women are higher in openness to creativity than men.",
      },
      veryHigh: {
        part1: "You are very high in openness to creativity, which means you love beauty, art, music, etc.",
        part2: "Those high in creativity need an outlet for their creative ability, or they will wither. They also need environment to match their creative personality. For example, they are sensitive to color and architectural form, and like to collect creative trinkets They have a powerful imagination and can get lost reflecting on things. They moved by music, books, movies, and any other form of stories to the point that they may be oblivious to the outside world. They respond very strongly to beauty, creativity and art and may be creative themselves in those areas.",
        part3: "Note: The higher the creativity, the more impractical or flighty they may be (especially if low in conscientiousness). The means they may have a very hard time monetizing their creativity or turning it into a career. However, creativity is necessary for entrepreneurial success.",
        part4: "Women are higher in openness to creativity than men.",
      },
    },
    aspect2: {
      aspectName: Aspect.Intellect,
      veryLow: {
        part1: "People very low in interest in ideas dislike to be overloaded with complex information. They are not curious or exploratory and do not like to tackle or solve problems. They are averse to engage or enjoy issue-oriented discussion or readings. They are less articulate and have difficulty in formulating and communicating their ideas (especially if low in extraversion). People very low in interest in ideas do not seek out or develop new or creative ideas, finding it difficult to adapt to new experiences and situations.",
        part2: "People very low in interest in ideas do not like complex occupations and are better suited for stable, straightforward, and more traditional occupations, where the rules for success are well-defined and tend not to change.",
        part3: "Women are lower than men in in ideas (although not in IQ).",
        part4: "Note: Do not confuse the personality aspect with IQ. This aspect measures interest in abstract ideas, while IQ is a measure of processing speed, verbal ability, working memory, and problem-solving capacity, and is better measured with a formal IQ test. It is perfectly possible to have a high IQ and a low score on the personality trait of interest in ideas or the reverse",
      },
      low: {
        part1: "People low in interest in ideas dislike to be overloaded with complex information. They are not curious or exploratory and do not like to tackle or solve problems. They are averse to engage or enjoy issue-oriented discussion or readings. They are less articulate and have difficulty in formulating and communicating their ideas (especially if low in extraversion). People low in interest in ideas do not seek out or develop new or creative ideas, finding it difficult to adapt to new experiences and situations",
        part2: "People low in interest in ideas do not like complex occupations and are better suited for stable, straightforward, and more traditional occupations, where the rules for success are well-defined and tend not to change.",
        part3: "Women are lower than men in in ideas (although not in IQ).",
        part4: "Note: Do not confuse the personality aspect with IQ. This aspect measures interest in abstract ideas, while IQ is a measure of processing speed, verbal ability, working memory, and problem-solving capacity, and is better measured with a formal IQ test. It is perfectly possible to have a high IQ and a low score on the personality trait of interest in ideas (or the reverse).",
      },
      modLow: {
        part1: "People moderately low in interest in ideas don’t like to be overloaded with complex information. They are less curious and exploratory and do not like to tackle or solve problems. They are less likely to engage or enjoy issue-oriented discussion or readings. They are usually less articulate and have difficulty in formulating and communicating their ideas (especially if low in extraversion). People moderately low in interest in ideas are less likely to seek out or develop new or creative ideas, finding it difficult to adapt to new experiences and situations.",
        part2: "People moderately low in interest in ideas do not like complex occupations and are better suited for stable, straightforward, and more traditional occupations, where the rules for success are well-defined and tend not to change.",
        part3: "Women are lower than men in in ideas (although not in IQ).",
        part4: "Note: Do not confuse the personality aspect with IQ. This aspect measures interest in abstract ideas, while IQ is a measure of processing speed, verbal ability, working memory, and problem-solving capacity, and is better measured with a formal IQ test. It is perfectly possible to have a high IQ and a low score on the personality trait of interest in ideas (or the reverse)",
      },
      average: {
        part1: "People average in interest in ideas can enjoy learning but are drawn to engaging in novel situations or information, especially if it is complex. They normal level of curious but are not exploratory, nor do they like to tackle and solve problems. On occasion and if it is an interest of their, they will engage, seek, and initiate issue-oriented discussions.",
        part2: "They have an average appreciation of reading, writing, and thinking, but they may only do so if there is a need or special occasion.  They may struggle to be articulate and be a bit slower to formulate ideas clearly and quickly compared to those higher in this trait.",
        part3: "People average in interest of ideas can develop new and creative concepts but are not compelled to do so.  They may look for new experience and situations, if encouraged to do so and they are slightly higher in extraversion. However, they are well-suited to stable, straightforward, and more traditional occupations.",
        part4: "Women are lower than men in their interest in ideas (although not in IQ).",
        Part5: "Note: Do not confuse the personality aspect with IQ. This aspect measures interest in abstract ideas, while IQ is a measure of processing speed, verbal ability, working memory, and problem-solving capacity, and is better measured with a formal IQ test. It is perfectly possible to have a high IQ and a low score on the personality trait of interest in ideas (or the reverse)."
      },
      modHigh: {
        part1: "People high in interest in ideas enjoy learning and engaging in novel information, even when it is complex. They are very curious and exploratory and like to tackle and solve problems. They engage, seek, and initiate issue-oriented discussions.",
        part2: "They read, think, and want to discuss information they consume (most frequently non-fiction), which also makes them articulate and allows them to formulate ideas clearly and quickly (especially if high in extraversion).",
        part3: "People high in interest of ideas develop new and creative concepts and search for new experience and situations, which also leads them to find complex occupations. However, they are less well-suited to stable, straightforward, and more traditional occupations, where they will experience frequent periods of boredom and frustration in such positions.",
        part4: "Women are lower than men in their interest in ideas (although not in IQ).",
        part5: "Note: Do not confuse the personality aspect with IQ. This aspect measures interest in abstract ideas, while IQ is a measure of processing speed, verbal ability, working memory, and problem-solving capacity, and is better measured with a formal IQ test. It is perfectly possible to have a high IQ and a low score on the personality trait of interest in ideas (or the reverse)."
      },
      high: {
        part1: "People high in interest in ideas enjoy learning and engaging in novel information, even when it is complex. They are very curious and exploratory, and like to tackle and solve problems. They engage, seek, and initiate issue-oriented discussions.",
        part2: "They read, think, and want to discuss information they consume (most frequently non-fiction), which also makes them articulate and allows them to formulate ideas clearly and quickly (especially if high in extraversion).",
        part3: "People high in interest of ideas develop new and creative concepts and search for new experience and situations, which also leads them to find complex occupations. However, they are less well-suited to stable, straightforward, and more traditional occupations, where they will experience frequent periods of boredom and frustration in such positions.",
        part4: "Women are lower than men in their interest in ideas (although not in IQ). ",
        part5: "Note: Do not confuse the personality aspect with IQ. This aspect measures interest in abstract ideas, while IQ is a measure of processing speed, verbal ability, working memory, and problem-solving capacity, and is better measured with a formal IQ test. It is perfectly possible to have a high IQ and a low score on the personality trait of interest in ideas (or the reverse)."
      },
      veryHigh: {
        part1: "People very high in interest in ideas enjoy learning and engaging in novel information, even when it is complex. They are very curious and exploratory, and like to tackle and solve problems. They engage, seek, and initiate issue-oriented discussions.",
        part2: "They read, think, and want to discuss information they consume (most frequently non-fiction), which also makes them articulate and allows them to formulate ideas clearly and quickly (especially if high in extraversion).",
        part3: "People very high in interest of ideas develop new and creative concepts and search for new experience and situations, which also leads them to find complex occupations. However, they are less well-suited to stable, straightforward, and more traditional occupations, where they will experience frequent periods of boredom and frustration in such positions.",
        part4: "Women are lower than men in their interest in ideas (although not in IQ).",
        part5: "Note: Do not confuse the personality aspect with IQ. This aspect measures interest in abstract ideas, while IQ is a measure of processing speed, verbal ability, working memory, and problem-solving capacity, and is better measured with a formal IQ test. It is perfectly possible to have a high IQ and a low score on the personality trait of interest in ideas (or the reverse)."
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Conscientiousness,
      veryLow: {
        part1: "You are very low in conscientiousness and may be described as very relaxed, distractable, present-minded, laid back, undisciplined, and guilt-free. You have strong desire for leisure and are indifferent to making and adhering to plans, finding little need for to-do lists, planners, or even defining days as organized and orderly.",
        part2: "Those very low in conscientiousness greatly enjoy inactivity and don’t consider it wasting time. They are very likely to procrastinate (especially, if low in neuroticism), and are more prone to giving excuses. This means that they may need to be pushed or constantly managed to work hard, especially the longer the task.",
        part3: "Very low conscientious people may be late or delayed because they are very easily distracted or place less emphasis on meeting a “time”. Because they are not focused on “doing things exactly by the book”, they may be better at solving novel problems (if they can be motivated to solve them), be more flexible if plans suddenly change, or open to “other people’s ideas, opinions, or solutions even if it falls outside the “correct way of doing something”. Family and cultural traditions are less important to them.",
        part4: "Academically, they struggle (particularly if they are low in openness) and are not concerned by failing or meeting goals. Also, they do not like to believe that hard work and focus equate to success, while believing luck is more important.  However, because of this they will be less judgmental, less frustrated by failures or mishaps (of others or themselves), and usually do not wrestle with shame or guilt over failure; however, they do think overworks are pushovers, teacher’s pets, or brown-nosers.",
        part5: "Note: The lower you are in conscientiousness, the easier it will be to relax and live in the moment; however, other people (especially those high that are disagreeable and higher in conscientiousness) may react negatively to your tendency to slack off, lack of order or cleanliness, or lack of responsibility.",
        part6: "Important: Conscientiousness is the second-best predictor of lifetime success (under general intelligence). It also nested in the other personality traits, and by focusing on micro-plans to help improve your industriousness, orderliness, and proactiveness, you can help mitigate anxiety, depression, and maladaptive strategies. ",
      },
      low: {
        part1: "You are low in conscientiousness and may be described as very relaxed, distractable, present-minded, laid back, undisciplined, and guilt-free. You have strong desire for leisure and are indifferent to making and adhering to plans, finding little need for to-do lists, planners, or even defining days as organized and orderly.",
        part2: "Those low in conscientiousness greatly enjoy inactivity and don’t consider it wasting time. They are very likely to procrastinate (especially, if low in neuroticism), and are more prone to giving excuses. This means that they may need to be pushed or constantly managed to work hard, especially the longer the task.",
        part3: "Low conscientious people may be late or delayed because they are very easily distracted or place less emphasis on meeting a “time”. Because they are not focused on “doing things exactly by the book”, they may be better at solving novel problems (if they can be motivated to solve them), be more flexible if plans suddenly change, or open to “other people’s ideas, opinions, or solutions even if it falls outside the “correct way of doing something”. Family and cultural traditions are less important to them.",
        part4: "cademically, they struggle (particularly if they are low in openness) and are not concerned by failing or meeting goals. Also, they do not like to believe that hard work and focus equate to success, while believing luck is more important.  However, because of this they will be less judgmental, less frustrated by failures or mishaps (of others or themselves), and usually do not wrestle with shame or guilt over failure; however, they do think overworks are pushovers, teacher’s pets, or brown-nosers.",
        part5: "Note: The lower you are in conscientiousness, the easier it will be to relax and live in the moment; however, other people (especially those high that are disagreeable and higher in conscientiousness) may react negatively to your tendency to slack off, lack of order or cleanliness, or lack of responsibility.",
        part6: "Important: Conscientiousness is the second-best predictor of lifetime success (under general intelligence). It also nested in the other personality traits, and by focusing on micro-plans to help improve your industriousness, orderliness, and proactiveness, you can help mitigate anxiety, depression, and maladaptive strategies. ",
      },
      modLow: {
        part1: "You are moderately low in conscientiousness and may be described as relaxed, distractable, present-minded, laid back, undisciplined, and guilt-free. You have more of a desire for leisure and are not so much concerned with making and adhering to plans, such as utilizing to-do lists or planners that aide in a more organized and orderly day.",
        part2: "Those moderately low in conscientiousness can easier enjoy inactivity and don’t consider it wasting time. They are more likely to procrastinate (especially, if low in neuroticism), and are more prone to giving excuses. This means that they may need to be pushed or constantly managed to work hard, especially the longer the task.",
        part3: "Moderately low conscientious people may be late or delayed because they easily distracted and may be less dependable or responsible. Because they are note focused on “doing things exactly by the book”, they may be better at solving novel problems, be more flexible if plans suddenly change, or open to “other people’s ideas, opinions, or solutions even if it falls outside the “correct way of doing something”. Family and cultural traditions are less important to them.",
        part4: "Academically, they tend to struggle (particularly if they are low in openness) and are not concerned by failing or meeting goals. Also, they will be more inclined to believe that hard work and focus don’t always equate to success, while believing luck is more important.  However, because of this they will be less judgmental, less frustrated by failures or mishaps (of others or themselves), and usually do not wrestle with shame or guilt over failure; however, they do think overworks are pushovers, teacher’s pets, or brown-nosers.",
      },
      average: {
        part1: "You are average in conscientiousness, which means you can strike a balance between hardworking and focused on details and relaxation and leisure. You may utilize plans, to-do lists, or planners if you want an organized and orderly day, but you may also have days that are unplanned.",
        part2: "Those average in conscientiousness tend to be more active than inactive, being slightly annoyed by wasting time, procrastinating (especially, if low in neuroticism), and excuses. Those average in conscientious people usually do what they say but may become distracted. They can face challenges and setbacks appropriately but may choose not to work long hours or even take on extra work if they can complete it another day.",
        part3: "People average in conscientiousness may be organized, future-oriented, and reliable unless there is a reason specific reason. They are aware of the importance of “doing things by the book”, but may be flexible if plans, ideas, or work change, or open to “other people’s ideas or opinions. They may enjoy family and cultural traditions.",
        part4: "cademically, they do well (particularly if they are also intelligent) but may need to be pushed or managed on occasion. They strike a balance in thinking that hard work should be rewarded and sometimes luck is important, too. They can be somewhat judgmental of others and unnerved by their own failures or mishaps depending on the situation.",
        part5: "Those average in conscientiousness tend to have normal feelings of guilt and shame around failure, loss of employments, or unfortunate events, even if it is not their fault.",
        part6: "",
      },
      modHigh: {
        part1: "You are moderately high in conscientiousness, which means you are hardworking, focused on details, clean, and drawn to duty. You usually make and adhere to plans, to-do lists, or planners because you usually want an organized and orderly day.",
        part2: "Those moderately high in conscientiousness do not like inactivity. This includes wasting time, procrastinating (especially, if low in neuroticism), and excuses. Conscientious people are faithful to do what they say. Because they are not easily distracted, even by leisure, they may be viewed as someone who overworks or can’t relax; however, they have a strong ability to persevere in the face of challenges and setback, have high endurance to work long hours, or even take on extra work.",
        part3: "People moderately high in conscientiousness are organized, future-oriented, and reliable. Because of this they are likely to be focused on details and “doing things exactly by the book”. Because they do things strictly by the book, it may be difficult to solve novel problems, be flexible if plans suddenly change, or open to “other people’s ideas or opinions. Family and cultural traditions are very important to them.",
        part4: "Academically, they do well (particularly if they are also intelligent) and are good at taking responsibility or adhering to duty. They believe (especially if low in agreeableness) that those who work hard should be rewarded, and that those who don’t usually bring it on themselves. They can be somewhat judgmental of others and unnerved by their own failures or mishaps. ",
        part5: "Those moderately high in conscientiousness tend to feel more guilt and shame. Because of this, they have a strong reaction to failure, loss of employments, or unfortunate events, even if it is not their fault (especially, if higher in neuroticism). However, they are less likely to react with outbursts of anger when feeling this way, feeling disappointment instead.",
        part6: "",
      },
      high: {
        part1: "You are high in conscientiousness and are very hardworking, focused on details, clean, and drawn to duty. You have a strong proclivity to make and adhere to plans, to-do lists, or planners because you desire an organized and orderly day.",
        part2: "Those high in conscientiousness are uncomfortable if not agitated by inactivity. They do not like wasting time, procrastinating (especially, if low in neuroticism), and excuses. Conscientious people are very faithful to do what they say. Because they are not easily distracted, even by leisure, they may be viewed as someone who overworks or can’t relax; however, they have a strong ability to persevere in the face of challenges and setback, have high endurance to work long hours, or even take on extra work.",
        part3: "People high in conscientiousness are very organized, future-oriented, and reliable. Because of this they are likely to be focused on details and “doing things exactly by the book”. Because they do things strictly by the book, it may be difficult to solve novel problems, be flexible if plans suddenly change, or open to “other people’s ideas or opinions. Family and cultural traditions are very important to them.",
        part4: "Academically, they do very well (particularly if they are also intelligent) and are also committed to responsibility or duty. They believe (especially if low in agreeableness) that those who work hard should be rewarded, and that those who don’t usually bring it on themselves. They can be judgmental of others and disgusted by their own failures or mishaps.",
        part5: "Those high in conscientiousness are also prone to guilt and shame. Because of this, they react strongly to failure, loss of employments, or unfortunate events, even if it is not their fault (especially, if higher in neuroticism). However, they are less likely to react with outbursts of anger when feeling this way, feeling disappointment instead.",
        part6: "Note: They can be hyper-concerned with hygiene, moral purity, and achievement. They can be very micro-managing and controlling and in extreme cases struggle with obsessive-compulsive tendencies, burn-out, and even anorexia.",
      },
      veryHigh: {
        part1: "You are very high in conscientiousness and are extremely hardworking, focused on details, clean, and drawn to duty. You have an incredibly strong proclivity make and adhere to plans, to-do lists, or planners because you strive for an organized and orderly day.",
        part2: "Those very high in conscientiousness are very uncomfortable if not agitated by inactivity. They hate wasting time, procrastinating (especially, if low in neuroticism), and giving excuses. Conscientious people are faithful to do what they say. Because they are not easily distracted, even by leisure, they may be viewed as someone who overworks or can’t relax; however, they have a strong ability to persevere in the face of challenges and setback, have high endurance to work long hours, or even take on extra work.",
        part3: "People very high in conscientiousness are extremely organized, future-oriented, and reliable. Because of this they are likely to be obsessed with details and “do things exactly by the book”, which may make it difficult to solve novel problems, be flexible if plans suddenly change, or open to “other people’s ideas or opinions. Family and cultural traditions are very important to them.",
        part4: "Academically, they do very well (particularly if they are also intelligent) and are also extremely committed to responsibility or duty. They are convinced (especially if low in agreeableness) that those who work hard should and will be rewarded, and that those who don’t deserve their failure. Also, they can come across as judgmental and be easily disgusted even by their own failures or mishaps.",
        part5: "Those very high in conscientiousness are also very prone to guilt and shame. Because of this, they react very intensely to failure, loss of employments, or unfortunate events, even if it is not their fault (especially, if higher in neuroticism). However, they are less likely to react with outbursts of anger when feeling this way, feeling disappointment instead.",
        part6: "Note: They can be hyper-concerned with hygiene, moral purity, and achievement. They can be very micro-managing and controlling and in extreme cases struggle with obsessive-compulsive tendencies, burn-out, and struggle with taking time off.",
      },
    },
    aspect1: {
      aspectName: Aspect.Industriousness,
      veryLow: {
        part1: "You are very low in industriousness, which means you are rarely driven or excited about work or action. If you are high in openness, you are likely to be regarded as an extreme underachiever.",
        part2: "Those very low in industriousness find it extremely difficult to focus on work and struggle with procrastinating, missing deadlines, or failing to complete assignments or projects. They easily forget or disregard responsibilities, and aren’t concerned with schedules, timelines, or getting tasks done quickly. They need to be supervised constantly to complete tasks because they lack focus and are easily distracted.",
        part3: "People very low in industriousness are nonjudgmental, will easily accept excuses, and give people the benefit of the doubt. They do not like to think that people fail because they don’t apply themselves, believing fate or bad luck is more of a factor. They are not as sensitive to guilt, disgust, or shame, have a very relaxed attitude toward life or life goals.",
        part4: "Men are slightly more industrious than women.",
      },
      low: {
        part1: "You are low in industriousness, which means you are not driven or excited about work or action. If you are high in openness, you are likely to be regarded as an underachiever.",
        part2: "Those low in industriousness don’t focus on work and struggle with procrastinating, missing deadlines, or failing to complete assignments or projects. They will put off responsibilities, aren’t concerned with schedules, timelines, or getting tasks done quickly. They need to be supervised constantly to complete tasks because they lack focus and are easily distracted.",
        part3: "People low in industriousness nonjudgmental, will easily accept excuses, and give people the benefit of the doubt. They do not like to think that people fail because they don’t apply themselves, believing fate or bad luck is more of a factor. They are not as sensitive to guilt, disgust, or shame, have a very relaxed attitude toward life or life goals.",
        part4: "Men are slightly more industrious than women.",
      },
      modLow: {
        part1: "You are moderately low in industriousness, which means you are not very driven or excited about work or action. If you are high in openness, you are likely to be regarded as an underachiever.",
        part2: "Those moderately low in industriousness don’t focus on work and may struggle with procrastinating, missing deadlines, or failing to complete assignments or projects. They tend to put off responsibilities, aren’t particularly concerned with schedules, timelines, or getting tasks done quickly. They need to be supervised often to complete tasks because they lack focus and are easily distracted.",
        part3: "People moderately low in industriousness do not judge themselves or others regarding work and will be more likely to accept excuses or give people the benefit of the doubt . They are averse to think that people fail because they don’t apply themselves, believing fate or bad luck is more of a factor. They are not as sensitive to guilt, disgust, or shame, have a more relaxed attitude toward life or life goals.",
        part4: "Men are slightly more industrious than women",
      },
      average: {
        part1: "You are average in industriousness, which means you can balance the drive to get things done with relaxing. You can more easily separate life and work, and aren’t necessarily, frustrated with work or leisure.",
        part2: "Those average in industriousness are understand what they are supposed to do but are not obsessed with it or duty bound by it.  They usually find a balance with completing tasks and making mistakes and may not be as sensitive to failing as that are higher in this trait. They find the benefits of a schedule but aren’t compelled to be on one. They can be focused on completing tasks, but it is not a race or a competitions for them.",
        part3: "Those average in industrious will easily be able to see over or under achievers and be slightly annoyed at both. They believe that people fail because they don’t apply themselves or work hard enough, but they aren’t above having sympathy or belief that luck could help. They are less sensitive to feeling guilty if they don’t fail in their schedule, plan, or specific job or duty. In most cases, know how to enjoy free time.",
        part4: "Men are slightly more industrious than women.",
      },
      modHigh: {
        part1: "You are moderately high in industriousness, which means you are driven to do. You view life and work about the same, and you prefer to be doing something useful over doing nothing.",
        part2: "Those moderately high are driven by duty, and they don’t like to put things off, make mistakes, or fail to finish what they start. Because of this they prefer to be on a schedule. They are focused on accomplishing more in less time regardless of resources and have a strong focus.",
        part3: "Those high in industrious tend to judge laziness or people who are incompetent, and they will attempt to remove those people from their work or lives. They believe that people fail because they don’t apply themselves or work hard enough. They can feel guilty if they don’t fail in their schedule, plan, or specific job or duty. In most cases, they must schedule in specific leisure or leisure activities, or they will be very uncomfortable with that free time.",
        part4: "Men are slightly more industrious than women.",
      },
      high: {
        part1: "You are high in industriousness, which means you are very driven to do. You view life and work the same, and you must always be doing something useful.",
        part2: "Those high in industriousness will struggle to relax or do nothing. Because they are very much driven by duty, they never put things off, hate making mistakes, finish what they start, and are always on a schedule. They are driven to accomplishing more in less time regardless of resources and have exceptional focus.",
        part3: "Those high in industrious are quick to judge laziness or people who are incompetent, and they will attempt to remove those people from their work or lives. There is a strong belief that people fail because they don’t apply themselves or work hard enough. They can feel guilty if they don’t fail in their schedule, plan, or specific job or duty. In most cases, they must be taught how to have leisure, or they will eventually be overcome by burnout.",
        part4: "Men are slightly more industrious than women.",
      },
      veryHigh: {
        part1: "You are very high in industriousness, which means you are extremely driven to do. You view life and work the same, and you must always be doing something useful.",
        part2: "Those very high in industriousness will always struggle to relax or do nothing. Because they are very much driven by duty, they never put things off, hate making mistakes, finish what they start, and are always on a schedule. They are always obsessed with accomplishing more in less time regardless of resources and have exceptional focus.",
        part3: "Those very high in industrious are quick to judge laziness or people who are incompetent, and they will attempt to remove those people from their work or lives. There is a strong belief that people fail because they don’t apply themselves or work hard enough. They can feel extremely guilty if they don’t fail in their schedule, plan, or specific job or duty. They have to work hard at learning to have leisure or will eventually be overcome by burnout.",
        part4: "Men are slightly more industrious than women.",
      },
    },
    aspect2: {
      aspectName: Aspect.Orderliness,
      veryLow: {
        part1: "You are very low in orderliness, which means you don’t orient your life in clean and ordered way. You don’t mind mess and chaos and may sometimes prefer it. This can also impact the way you think, which means things can’t always be divided up into two groups: black and white, good and bad, or acceptable and unacceptable because from your viewpoint there are a lot of grey areas.",
        part2: "Those that are very low in orderliness don’t like to make and stick to schedules because if feels to rigid, don’t feel the need to have a proper place for everything (including ideas and beliefs), and don’t mind if things become scattered. They don’t like be focused on details, rules, and morality. For this reason, they almost lack a judgmental, harsh, and punitive towards attitude toward themselves and others if order is disturbed. They usually become upset if there is too much routine.",
        part3: "Being very low in orderliness can mean struggling or extremely disliking complex tasks or careers, and tend to be more creative because creativity allows you to explore outside the normal boundaries.",
        part4: "NOTE: Women are more orderly than men, which is why there is struggle with housework between women and men. Women will more often be disgusted with household disorder faster than males. Communication over chores that deal with organizing and cleanliness is extremely important if resentment or unfair distribution of chores is to be avoided.",
      },
      low: {
        part1: "You are low in orderliness, which means you don’t orient your life in clean and ordered way. You don’t mind mess and chaos and may sometimes prefer it. This can also impact the way you think, which means things can’t always be divided up into two groups: black and white, good and bad, or acceptable and unacceptable because from your viewpoint there are a lot of grey areas.",
        part2: "Those that are low in orderliness don’t like to make and stick to schedules because if feels to rigid, don’t feel the need to have a proper place for everything (including ideas and beliefs), and don’t mind if things become scattered. They don’t like be focused on details, rules, and morality. For this reason, they almost lack a judgmental, harsh, and punitive towards attitude toward themselves and others if order is disturbed. They usually become upset if there is too much routine.",
        part3: "Being low in orderliness can mean struggling or extremely disliking complex tasks or careers, and tend to be more creative because creativity allows you to explore outside the normal boundaries.",
        part4: "NOTE: Women are more orderly than men, which is why there is struggle with housework between women and men. Women will more often be disgusted with household disorder faster than males. Communication over chores that deal with organizing and cleanliness is extremely important if resentment or unfair distribution of chores is to be avoided.",
      },
      modLow: {
        part1: "You are moderately low in orderliness, which means you usually don’t orient your life in clean and ordered way. You usually don’t mind mess and chaos. This can also impact the way you think, which is less black and white. In other words, things don’t always fall into a good or bad and acceptable or unacceptable group because of their being appropriate grey areas.",
        part2: "Those that are moderately low in orderliness usually don’t make and stick to schedules, don’t necessary have proper place for everything (including ideas and beliefs), and don’t mind if things become scattered. They would prefer to not be focused on details, rules, and morality. For this reason, they are less judgmental, harsh, and punitive towards themselves and others if their order is disturbed. They usually don’t become upset without routine.",
        part3: "Being moderately low in orderliness can mean struggling at managing complex tasks, but may be more creative because creativity allows you to explore outside the normal boundaries",
        part4: "NOTE: Women are more orderly than men, which is why there is struggle with housework between women and men. Women will more often be disgusted with household disorder faster than males. Communication over chores that deal with organizing and cleanliness is extremely important if resentment or unfair distribution of chores is to be avoided.",
      },
      average: {
        part1: "You are average in orderliness, which means you are neither disturbed nor disgusted by mess and chaos as much as those higher in this trait.",
        part2: "On average, you are moderately tidy and organized, and aren’t forced to think in terms of simple black and white. You aren’t always reliant on schedules, lists or routines, unless it is needed, and same goes for your focus on detail, rules or general morality.",
        part3: "Most of the time you prefer routine and predictability but don’t become as upset if things are disrupted. For the most part you do well with complexity, but you may have to be reminded to pay proper attention and maintain focus. There is better tolerance for mess, disruption and chaos, which makes you slightly more creative.",
        part4: "NOTE: Women are more orderly than men, which is why there is struggle with housework between women and men. Women will more often be disgusted with household disorder faster than males. Communication over chores that deal with organizing and cleanliness is extremely important if resentment or unfair distribution of chores is to be avoided.",
      },
      modHigh: {
        part1: "You are moderately high in orderliness, which means you try to orient your life in clean and ordered way. You usually disturbed and disgusted by mess and chaos. This can also impact the way you think, which is black and white. In other words, things are good or bad and acceptable or unacceptable. There are usually no grey areas.",
        part2: "Those moderately high in orderliness prefer to make and stick to schedules, have a proper place for everything (including ideas and beliefs), and most importantly like things to stay where they belong. They can focused on details, rules, and morality. For this reason, they can be judgmental, harsh, and punitive towards themselves and others if their order is disturbed. They can become upset without routine.",
        part3: "Being moderately high in orderliness can mean being skilled at managing complex tasks, but at the cost of creativity because creativity can be viewed as messy, disruptive, and chaotic.",
        part4: "NOTE: Women are more orderly than men, which is why there is struggle with housework between women and men. Women will more often be disgusted with household disorder faster than males. Communication over chores that deal with organizing and cleanliness is extremely important if resentment or unfair distribution of chores is to be avoided.",
      },
      high: {
        part1: "You are high in orderliness, which means you try to orient your life in clean and ordered way. You are disturbed and disgusted by mess and chaos. This can also impact the way you think, which is black and white. In other words, things are good or bad and acceptable or unacceptable. There are almost no grey areas.",
        part2: "Those high in orderliness make and stick to schedules, have a proper place for everything (including ideas and beliefs), and most importantly like things to stay where they belong. They can obsess over details, rules, and morality. For this reason, they can be very judgmental, harsh, and punitive towards themselves and others if their order is disturbed. They are extremely agitated without routine.",
        part3: "Being high in orderliness can mean being skilled at managing complex tasks, but are less creative because creativity can be viewed as messy, disruptive and chaotic.",
        part4: "NOTE: Women are more orderly than men, which is why there is struggle with housework between women and men. Women will more often be disgusted with household disorder faster than males. Communication over chores that deal with organizing and cleanliness is extremely important if resentment or unfair distribution of chores is to be avoided.",
      },
      veryHigh: {
        part1: "You are very high in orderliness, which means you try to orient your life in clean and ordered way. You are very disturbed and disgusted by mess and chaos. This can also impact the way you think, which is black and white. In other words, things are good or bad and acceptable or unacceptable. There are no grey areas.",
        part2: "Those very high in orderliness make and stick to schedules, have a proper place for everything (including ideas and beliefs), and most importantly like things to stay where they belong. They can obsess over details, rules, and morality. For this reason, they can be very judgmental, harsh, and punitive towards themselves and others if their order is disturbed. They are extremely agitated without routine.",
        part3: "Being very high in orderliness can mean being skilled at managing complex tasks, but are less creative because creativity can be viewed as messy, disruptive and chaotic.",
        part4: "NOTE: Women are more orderly than men, which is why there is struggle with housework between women and men. Women will more often be disgusted with household disorder faster than males. Communication over chores that deal with organizing and cleanliness is extremely important if resentment or unfair distribution of chores is to be avoided.",
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Extraversion,
      veryLow: {
        part1: "test",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect1: {
      aspectName: Aspect.Enthusiasm,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Assertiveness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Agreeableness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "You are very high in agreeableness and are extremely generous, nice, and nurturing.",
        part2: "Very high agreeable people will almost always see the best in others and will strongly act accordingly. For example, they do not like feelings hurt, care more about the emotions/interests of others, and desire or are motivated to keeping the peace, even if come across as overbearing or micromanaging.",
        part3: "Those very high in agreeableness think it is very important to be forgiving, cooperative, accepting, flexible, gentle, and patient. They feel others’ emotions and may overwhelmingly feel empathy or pity for those who are excluded, punished, or defeated, which causes intense distrust of competition.",
        part4: "People very high in agreeableness are very susceptible to be taken advantage of, have a very high avoidance of arguments or heated discussions. Behaviorally, they may be too self-sacrificing in romantic partnerships, family relationships, friendships, career settings. If this behavior is ignored to the individual’s detriment, it can create resentment, hidden anger, or passive-aggression if they are higher in neuroticism or extreme passive conformity if they are lower in neuroticism. Their over-protectiveness can clash or block individual agency of those they care about or oversee.",
      },
    },
    aspect1: {
      aspectName: Aspect.Compassion,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Politeness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Neuroticism,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect1: {
      aspectName: Aspect.Withdrawal,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Volatility,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
];

export default interpretations;
