import { Aspect, Ocean } from "./schema";
const interpretations: any = [
  {
    category: {
      categoryName: Ocean.Openness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect1: {
      aspectName: Aspect.AestheticOpenness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Intellect,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Conscientiousness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect1: {
      aspectName: Aspect.Industriousness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Orderliness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Extraversion,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect1: {
      aspectName: Aspect.Enthusiasm,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Assertiveness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Agreeableness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "You are very high in agreeableness and are extremely generous, nice, and nurturing.",
        part2: "Very high agreeable people will almost always see the best in others and will strongly act accordingly. For example, they do not like feelings hurt, care more about the emotions/interests of others, and desire or are motivated to keeping the peace, even if come across as overbearing or micromanaging.",
        part3: "Those very high in agreeableness think it is very important to be forgiving, cooperative, accepting, flexible, gentle, and patient. They feel others’ emotions and may overwhelmingly feel empathy or pity for those who are excluded, punished, or defeated, which causes intense distrust of competition.",
        part4: "People very high in agreeableness are very susceptible to be taken advantage of, have a very high avoidance of arguments or heated discussions. Behaviorally, they may be too self-sacrificing in romantic partnerships, family relationships, friendships, career settings. If this behavior is ignored to the individual’s detriment, it can create resentment, hidden anger, or passive-aggression if they are higher in neuroticism or extreme passive conformity if they are lower in neuroticism. Their over-protectiveness can clash or block individual agency of those they care about or oversee.",
      },
    },
    aspect1: {
      aspectName: Aspect.Compassion,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Politeness,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
  {
    category: {
      categoryName: Ocean.Neuroticism,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect1: {
      aspectName: Aspect.Withdrawal,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
    aspect2: {
      aspectName: Aspect.Volatility,
      veryLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      low: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modLow: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      average: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      modHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      high: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
      veryHigh: {
        part1: "",
        part2: "",
        part3: "",
        part4: "",
      },
    },
  },
];

export default interpretations;
