import { Aspect, Ocean, Question } from "./schema";

export const questionData: Question[] = [
  {
    uid: "q0",
    text: "Openness - Openness - normal",
    reverse: false,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q1",
    text: "Openness - Openness - reversed",
    reverse: true,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q2",
    text: "Openness - Intellect - normal",
    reverse: false,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q3",
    text: "Openness - Intellect - reversed",
    reverse: true,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q4",
    text: "Conscientiousness - Industriousness - normal",
    reverse: false,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q5",
    text: "Conscientiousness - Industriousness - reversed",
    reverse: true,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q6",
    text: "Conscientiousness - Orderliness - normal",
    reverse: false,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q7",
    text: "Conscientiousness - Orderliness - reversed",
    reverse: true,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q8",
    text: "Extraversion - Enthusiasm - normal",
    reverse: false,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q9",
    text: "Extraversion - Enthusiasm - reversed",
    reverse: true,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q10",
    text: "Extraversion - Assertiveness - normal",
    reverse: false,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q11",
    text: "Extraversion - Assertiveness - reversed",
    reverse: true,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q12",
    text: "Agreeableness - Compassion - normal",
    reverse: false,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q13",
    text: "Agreeableness - Compassion - reversed",
    reverse: true,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q14",
    text: "Agreeableness - Politeness - normal",
    reverse: false,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q15",
    text: "Agreeableness - Politeness - reversed",
    reverse: true,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q16",
    text: "Neuroticism - Withdrawal - normal",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q17",
    text: "Neuroticism - Withdrawal - reversed",
    reverse: true,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q18",
    text: "Neuroticism - Volatility - normal",
    reverse: false,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q19",
    text: "Neuroticism - Volatility - reversed",
    reverse: true,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
];
