import { Aspect, Ocean, Question } from "./schema";

export const questionData: Question[] = [
  {
    uid: "q0",
    text: "See beauty in things that others might not notice",
    reverse: false,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q1",
    text: "Rarely notice the emotional aspects of paintings and pictures",
    reverse: true,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q2",
    text: "Enjoy the beauty of nature",
    reverse: false,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q3",
    text: "Rarely get lost in thought",
    reverse: true,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q4",
    text: "Do not like poetry",
    reverse: true,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q5",
    text: "Rarely daydream",
    reverse: true,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q6",
    text: "Believe in the importance of art",
    reverse: false,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q7",
    text: "Love to reflect on things",
    reverse: false,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q8",
    text: "Get deeply immersed in music",
    reverse: false,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q9",
    text: "Need a creative outlet",
    reverse: false,
    aspect: Aspect.AestheticOpenness,
    ocean: Ocean.Openness,
  },
  {
    uid: "q10",
    text: "Learn things slowly",
    reverse: true,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q11",
    text: "Have difficulty understanding abstract ideas ",
    reverse: true,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q12",
    text: "Avoid philosophical discussions",
    reverse: true,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q13",
    text: "Avoid difficult reading material",
    reverse: true,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q14",
    text: "Have a rich vocabulary",
    reverse: false,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q15",
    text: "Can handle a lot of information",
    reverse: false,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q16",
    text: "Like to solve complex problems",
    reverse: false,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q17",
    text: "Am quick to understand things",
    reverse: false,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q18",
    text: "Think quickly",
    reverse: false,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q19",
    text: "Formulate ideas clearly",
    reverse: false,
    aspect: Aspect.Intellect,
    ocean: Ocean.Openness,
  },
  {
    uid: "q20",
    text: "Carry out my plans",
    reverse: false,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q21",
    text: "Finish what I start",
    reverse: false,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q22",
    text: "Get things done quickly",
    reverse: false,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q23",
    text: "Always know what I am doing",
    reverse: false,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q24",
    text: "Mess things up",
    reverse: true,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q25",
    text: "Don't put my mind on the task at hand ",
    reverse: true,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q26",
    text: "CFind it difficult to get down to work",
    reverse: true,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q27",
    text: "Waste my time",
    reverse: true,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q28",
    text: "Postpone decisions",
    reverse: true,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q29",
    text: "CAm easily distracted",
    reverse: true,
    aspect: Aspect.Industriousness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q30",
    text: "See that rules are observed",
    reverse: false,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q31",
    text: "Want every detail taken care of",
    reverse: false,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q32",
    text: "Like order",
    reverse: false,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q33",
    text: "Keep things tidy",
    reverse: false,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q34",
    text: "Follow a schedule",
    reverse: false,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q35",
    text: 'Want everything to be “just right"',
    reverse: false,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q36",
    text: "Am not bothered by messy people",
    reverse: true,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q37",
    text: "Am not bothered by disorder",
    reverse: true,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q38",
    text: "Leave my belongings around",
    reverse: true,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q39",
    text: "Dislike routine",
    reverse: true,
    aspect: Aspect.Orderliness,
    ocean: Ocean.Conscientiousness,
  },
  {
    uid: "q40",
    text: "Make friends easily",
    reverse: false,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q41",
    text: "Warm up quickly to others",
    reverse: false,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q42",
    text: "Have a lot of fun",
    reverse: false,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q43",
    text: "Show my feelings when I'm happy",
    reverse: false,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q44",
    text: "Laugh a lot",
    reverse: false,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q45",
    text: "Am hard to get to know",
    reverse: true,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q46",
    text: "Keep others at a distance",
    reverse: true,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q47",
    text: "Reveal little about myself",
    reverse: true,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q48",
    text: "Rarely get caught up in the excitement",
    reverse: true,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q49",
    text: "Am not a very excitable person",
    reverse: true,
    aspect: Aspect.Enthusiasm,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q50",
    text: "Take charge",
    reverse: false,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q51",
    text: "Have a strong personality",
    reverse: false,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q52",
    text: "Know how to captivate people",
    reverse: false,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q53",
    text: "See myself as a good leader",
    reverse: false,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q54",
    text: "Can talk others into doing things",
    reverse: false,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q55",
    text: "Am the first to act",
    reverse: false,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q56",
    text: "Do not have an assertive personality",
    reverse: true,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q57",
    text: "Lack the talent for influencing people",
    reverse: true,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q58",
    text: "Wait for others to lead the way",
    reverse: true,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q59",
    text: "Hold back my opinions",
    reverse: true,
    aspect: Aspect.Assertiveness,
    ocean: Ocean.Extraversion,
  },
  {
    uid: "q60",
    text: "Feel others' emotions",
    reverse: false,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q61",
    text: "Inquire about others' well-being",
    reverse: false,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q62",
    text: "Sympathize with others' feelings",
    reverse: false,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q63",
    text: "Take an interest in other people's lives",
    reverse: false,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q64",
    text: "Like to do things for others",
    reverse: false,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q65",
    text: "Rarely interested in other people's problems",
    reverse: true,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q66",
    text: "Can't be bothered with other's needs",
    reverse: true,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q67",
    text: "Am indifferent to the feelings of others",
    reverse: true,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q68",
    text: "Don't have a soft side",
    reverse: true,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q69",
    text: "Take no time for others ",
    reverse: true,
    aspect: Aspect.Compassion,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q70",
    text: "Respect authority",
    reverse: false,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q71",
    text: "Hate to seem pushy",
    reverse: false,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q72",
    text: "Avoid imposing my will on others",
    reverse: false,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q73",
    text: "Rarely put people under pressure",
    reverse: false,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q74",
    text: "Insult people",
    reverse: true,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q75",
    text: "Seek conflict",
    reverse: true,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q76",
    text: "Love a good fight",
    reverse: true,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q77",
    text: "Believe that I am better than others ",
    reverse: true,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q78",
    text: "Am out for my own personal gain",
    reverse: true,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q79",
    text: "Take advantage of others",
    reverse: true,
    aspect: Aspect.Politeness,
    ocean: Ocean.Agreeableness,
  },
  {
    uid: "q80",
    text: "Am filled with doubts about things",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q81",
    text: "Feel comfortable with myself",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q82",
    text: "Feel threatened easily",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q83",
    text: "Worry about things",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q84",
    text: "Am easily discouraged",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q85",
    text: "Become overwhelmed by events",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q86",
    text: "Often feel fearful",
    reverse: false,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q87",
    text: "Seldom feel unhappy",
    reverse: true,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q88",
    text: "Rarely feel depressed",
    reverse: true,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q89",
    text: "NAm not embarrassed easily",
    reverse: true,
    aspect: Aspect.Withdrawal,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q90",
    text: "Get angry easily",
    reverse: false,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q91",
    text: "Get upset easily",
    reverse: false,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q92",
    text: "My mood can change a lot",
    reverse: false,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q93",
    text: "Am a person whose moods go up and down easily",
    reverse: false,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q94",
    text: "Get easily agitated",
    reverse: false,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q95",
    text: "Can be stirred up easily",
    reverse: false,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q96",
    text: "Keep my emotions under control",
    reverse: true,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q97",
    text: "Rarely get irritated",
    reverse: true,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q98",
    text: "Am not easily annoyed",
    reverse: true,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
  {
    uid: "q99",
    text: "Rarely lose my self-control",
    reverse: true,
    aspect: Aspect.Volatility,
    ocean: Ocean.Neuroticism,
  },
];
